config/routes.rb
Arpameeting::Application.routes.draw do
  get "recharges/new"

  get "recharges/create"

  get "new/create"

  get "orders/new"

  get "sessions/new"

  resources :users, :only => [:show, :new, :create, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
 
  resources :orders, :only => [:new, :create]
  resources :recharges, :only => [:new, :create]
 
  resources :rooms
  resources :services, :only => [:index]
  
  
  match 'rooms/:id_room/participants/:id_participant' => 'rooms#show', :as => 'room_participant'
  
  match 'signup'    => 'users#new'
  match 'signin'    => 'sessions#new'
  match 'sessions'  => redirect('signin')
  match 'signout'   => 'sessions#destroy'

  match 'orders/new/express' => 'orders#express',:as => 'express_new_order'

  match 'api' => 'api_docs#index', :as => 'api_docs'

  namespace :api_v1, :path => 'api/1' do
    resources :rooms
    resources :services, :only => [:index]
  end
  

  root :to => "home#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :user
    has_one :phonebrowser_service
    has_one :video_service
    has_many :participants
    
    accepts_nested_attributes_for :participants
    
    def start
        phonebrowser_service.start
    end
    
    def price
        price = 0.0
        participants.each do |participant|
            price += participant.price
        end
        return price.round(2)
    end
    
end

app/controllers/api_v1/rooms_controller.rb
class ApiV1::RoomsController < ApiV1::APIController
    
    before_filter :check_api_signed_in, :only => [:index, :show, :create, :new, :update, :edit, :destroy]
    before_filter :check_owner, :only => [:show, :update, :edit, :destroy]

    def check_owner
        room = Room.find(params[:id])
        if room.user != current_user
            api_error '401', {:message => 'You must be the owner of the room to perform this action.'}
        end
    end
    
    def index
        if !signed_in?
            # TODO Show API permission error
        else
            @rooms = current_user.rooms
            api_respond @rooms
        end
    end
    
    def show
        @room = Room.find(params[:id])
        @room.phonebrowser_service.update_status
        api_respond @room, {:include => [:phonebrowser_service, :participants]}
        #@participant = Participant.find(params[:id_participant])
    end


    def create
        @room = Room.create(:user => current_user)
        participants_array = []
        if params[:room][:participant].class == Array
            participants_array = params[:room][:participant]
        else
            participants_array << params[:room][:participant]
        end
        participants_array.each do |part|
            p = Participant.new
            p.name = part[:name]
            p.phone = part[:phone]
            p.sip = part[:sip]
            p.browser = part[:browser]
            p.phonebrowser_service_id = Service.find_by_name('phonebrowser').id
            p.video_service_id = Service.find_by_name('video').id
            p.save
            @room.participants << p
        end
        @room.phonebrowser_service = PhonebrowserService.create(:room => @room)
        @room.video_service = VideoService.create(:room => @room)
        @room.save
        if params[:room][:start_now] and !params[:room][:start_now].nil? and params[:room][:start_now] == "1"
            @room.start
        end
        api_respond @room, {:include => [:phonebrowser_service, :participants]}
    end
    
    def update
        @room = Room.find(params[:id])
        if params[:room][:participant_attributes]
            params[:room][:participant_attributes].each do |part|
                @room.participants.find(part[0].to_i).update_attributes(part[1])
            end
        else
            if params[:room][:start_now] == "1"
                @room.start if !@room.nil?
            end
        end
        api_respond @room, {:include => [:phonebrowser_service, :participants]}
    end
    
    #def destroy
    #    @room = Room.find(params[:id])
    #    @room.destroy
    #    redirect_to rooms_path
    #end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    
    before_filter :check_signed_in, :only => [:index, :create, :new, :update, :edit, :destroy]
    before_filter :check_owner, :only => [:update, :edit, :destroy]
    
=begin
    
=end
    def check_owner
        room = Room.find(params[:id])
        if room.user != current_user
            flash[:notice] = 'You are not the owner of this room.'
            redirect_to rooms_path
        end
    end
    
    def index
        if !signed_in?
            redirect_to '/signin'
        else
            @rooms = current_user.rooms
            respond_to do |format|
                format.html
                format.xml {render :xml => @rooms}
            end
        end
    end
    
    def show
        @room = Room.find(params[:id_room])
        @room.phonebrowser_service.update_status
        @participant = Participant.find(params[:id_participant])
    end

=begin
    TODO Add user restriction.
=end
    def create
        @room = Room.create(:user => current_user)
        
        # Creation from web form.
        if params[:room][:participant_attributes]
            @room.phonebrowser_service = PhonebrowserService.create(:room => @room)
            @room.video_service = VideoService.create(:room => @room)
            params[:room][:participant_attributes].each do |part|
                p = Participant.new
                if part[:phonebrowser_service] == '1'
                    p.phonebrowser_service_id = Service.find_by_name('phonebrowser').id
                end
                if part[:video_service_id] == '1'
                    p.video_service_id = Service.find_by_name('video').id
                end
                p.name = part[:name]
                p.phone = part[:phone]
                p.sip = part[:sip]
                p.browser = part[:browser]
                p.save
                @room.participants << p
            end
            @room.save
            redirect_to rooms_path
            
        # Creation from RESTful request
        elsif params[:room][:participant]
            participants_array = []
            if params[:room][:participant].class == Array
                participants_array = params[:room][:participant]
            else
                participants_array << params[:room][:participant]
            end
            participants_array.each do |part|
                p = Participant.new
                p.name = part[:name]
                p.phone = part[:phone]
                p.sip = part[:sip]
                p.browser = part[:browser]
                p.save
                @room.participants << p
            end
            @room.phonebrowser_service = PhonebrowserService.create(:room => @room)
            @room.video_service = VideoService.create(:room => @room)
            @room.save
            if params[:room][:start_now] and !params[:room][:start_now].nil? and params[:room][:start_now] == "1"
                @room.start
            end
            # @ltest.to_xml(:include => :sub_tests) 
            respond_to do |format|
                format.html {redirect_to rooms_path}
                format.xml { render :xml => @room.to_xml(:include => [:phonebrowser_service, :participants]) } #.to_xml(:include => :phonebrowser_service)
                format.json {render :json => @room.to_json(:include => [:phonebrowser_service, :participants]) }
            end
        end
    end
    
    def new
        @services = Service.all
        @room = Room.new
        @room.participants << Participant.new
    end
    
    def edit
        @room = Room.find(params[:id])
    end
    
    def update
        @room = Room.find(params[:id])
        if params[:room][:participant_attributes]
            params[:room][:participant_attributes].each do |part|
                @room.participants.find(part[0].to_i).update_attributes(part[1])
            end
        else
            if params[:room][:start_now] == "1"
                @room.start if !@room.nil?
            end
        end
        respond_to do |format|
            format.html {redirect_to rooms_path}
            format.xml { render :xml => @room.to_xml(:include => [:phonebrowser_service, :participants]) } #.to_xml(:include => :phonebrowser_service)
            format.json {render :json => @room.to_json(:include => [:phonebrowser_service, :participants]) }
        end
    end
    
    def destroy
        @room = Room.find(params[:id])
        @room.destroy
        redirect_to rooms_path
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
    def add_participant_link(name)
        link_to_function name do |page|
            page.insert_html :bottom, :participants, :partial => 'participant', :object => Participant.new
        end
    end
end

app/views/rooms/_browser_room.html.erb
<% require 'cgi' %>
<div class="participant_input">
    <h2>You are: <%=@participant.name%></h2>
    <div id="input_audio_container"></div>
    <div id="input_video_container"></div>
    <script type="text/javascript">
        var url_audio_input = "<%= raw(@participant.pb_input_output_flash) %>";
        swfobject.embedSWF(url_audio_input, 'input_audio_container', 320, 240, '10.0.0');
        AMVideo.input.stream = "peer<%=@participant.id%>";
        AMVideo.input.container = "input_video_container";
    </script>
</div>

app/views/rooms/_edit_participant.html.erb
<div class="participant">
    <h2>Participant</h2>
    <%= fields_for "room[participant_attributes][]", edit_participant do |participant_form| %>
        <div class="field">
            <%= participant_form.label :name %><br />
            <%= participant_form.text_field :name %>
        </div>
        <div class="field">
            <%= participant_form.label :phone %><br />
            <%= participant_form.text_field :phone %>
        </div>
        <div class="field">
            <%= participant_form.label :sip %><br />
            <%= participant_form.text_field :sip %>
        </div>
        <div class="field">
            <%= participant_form.label :browser %><br />
            <%= participant_form.check_box :browser %>
        </div>
    <% end %>
</div>

app/views/rooms/_listener_room.html.erb
<% if !@room.phonebrowser_service.listener_uri.nil? %>
<div class="listener_participant">
    <h2>Audio</h2>
    <div id="listener_container"></div>
    <div id="input_video_container"></div>
    <script type="text/javascript">
        var url_audio_listener = '<%= @room.phonebrowser_service.listener_uri %>'
        swfobject.embedSWF(url_audio_listener, 'listener_container', 320, 240, '10.0.0');
        AMVideo.input.stream = "peer<%=@participant.id%>";
        AMVideo.input.container = "input_video_container";
    </script>
</div>
<% end %>

app/views/rooms/_partial_room.html.erb
<div class="grid_12">
    <h2>Room #<%= @room.id%></h2>
    <div style="text-align: center">
    <%= form_for @room do |room_form| %>
    <div class="actions">
        <%= room_form.hidden_field :start_now, {:value => "1"} %>
        <%= room_form.submit "Start Room", :class => "button" %>
    </div>
    <% end %>
    <%= link_to 'Edit', edit_room_path(@room) %> -
    <%= link_to 'Delete', @room, :method => :delete %> -
    <% if !@room.phonebrowser_service.nil? %>
        <%=link_to 'Enter as listener', @room.phonebrowser_service.listener_uri%>
    <% end %>
    <p>
    Price: <%= @room.price %> &euro;
    </p>
    </div>
    <% @room.participants.each do |participant| %>
        <h4>Participant #<%=participant.id%></h4>
        Name: <%= participant.name %> <br/>
        Contact: <%= participant.contact %> <br/>
        Video: <%= (!participant.video_service_id.nil?).to_s %> <br/>
        State: <%= participant.pb_call_state %> <br/>
        Started: <%= participant.pb_call_started %> <br/>
        Finished: <%= participant.pb_call_finished %> <br/>
        
        <%= link_to 'Enter as participant', room_participant_path(@room, participant)%><br/>
        <% if participant.contact != 'browser' %>
            <%= link_to 'Output Audio', participant.pb_output_recording  %> - 
            <%= link_to 'Input Audio', participant.pb_input_recording if participant.contact != 'browser'%>
        <% end %>
    <% end %>
    <hr />
</div>

app/views/rooms/_participant.html.erb
<div class="participant" style="margin-bottom: 10px">
    <h2>Participant</h2>
    <%= fields_for "room[participant_attributes][]", participant do |participant_form| %>
        <div class="services">
        <strong>Services</strong><br />
        <% @services.each do |service| %>
            <% if service.name == 'phonebrowser'%>
                <div class="field">
                <%= participant_form.check_box :phonebrowser_service, 
                {:checked => true, :disabled => true} %>
                PhoneBrowser Service <i>(mandatory)</i>
                </div>
            <% elsif service.name == 'video' %>
                <div class="field">
                <%= participant_form.check_box :video_service_id %>
                Videoconference Service
                </div>
            <% end %>
        <% end %>
        </div>
        <div class="field">
            <strong><%= participant_form.label :name %></strong><br />
            <%= participant_form.text_field :name %>
        </div>
        <strong>Contact information</strong>
        <p>Choose the media you will use the participant</p>
        <div class="field">
            <%= participant_form.label :phone %> <em>+{:international_code}{:phone_number}</em><br />
            <%= participant_form.text_field :phone %>
        </div>
        <div class="field">
            <%= participant_form.label :sip %> <em>{:user}@{:sip_server}</em><br />
            <%= participant_form.text_field :sip %>
        </div>
        <div class="field">
            <%= participant_form.label :browser %>
            <%= participant_form.check_box :browser %>
        </div>
        <%= link_to_function "- remove participant", "$(this).up('.participant').remove()" %>
    <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Edit room</h1>

<%= form_for @room do |room_form| %>
    
    <div id="participants">
    <%= render :partial => 'edit_participant', :collection => @room.participants %>
    </div>
    
    <%= label_tag :start_now%>
    <%= check_box_tag(:start_now) %>
    
    <div class="actions">
        <%= room_form.submit "Update" %>
    </div>

<% end %>

app/views/rooms/index.html.erb
<h1>Number of rooms: <%= @rooms.count %> </h1>
<div class="grid_12">
    <% @rooms.each do |@room| %>
        <% @room.phonebrowser_service.update_status if !@room.phonebrowser_service.nil?%>
        <%= render :partial => 'partial_room'%>
    <% end %>
</div>

app/views/rooms/new.html.erb
<h1>Create new room</h1>
<br/>
<%= form_for @room, :url => rooms_path do |room_form| %>
    <div id="participants">
    <%= render :partial => 'participant', :collection => @room.participants %>
    </div>
    <p><%= add_participant_link "+ add a participant" %></p>
    <div class="actions">
        <%= room_form.submit "Create" %>
    </div>
<% end %>

app/views/rooms/show.html.erb
<script type="text/javascript">
    AMVideo.net_group_name = '<%= @room.video_service.group_name %>';
</script>
<h1>Room #<%=@room.id%></h1>
<% if @participant.video_service_id.nil? %>
    <button id="add_video_button">Activate video</button>
    <script type="text/javascript">
        $('add_video_button').observe ('click', function ()
        {
            AMVideo.createInputSWF();
            $('add_video_button').hide();
        });
    </script>
<% end %>
<% if @participant.contact != "browser" %>
    <%= render :partial => 'listener_room'%>
<% elsif %>
    <%= render :partial => 'browser_room'%>
<% end %>
<script type="text/javascript">
    AMVideo.output.peers = [];
</script>
<div class="other_participants">
    <% @room.participants.each do |participant| %>
        <% if participant != @participant %>
            <div id="participant_<%= @participant.id %>">
                <h2><%=participant.name%></h2>
                <div id="participant_<%= participant.id %>_video"></div>
                <script type="text/javascript">
                AMVideo.output.peers.push({ stream : "peer<%= participant.id %>", container : "participant_<%= participant.id %>_video"});
                </script>
            </div>
        <% end %>
    <% end %>
</div>
<% if !@participant.video_service_id.nil? %>
    <script type="text/javascript">AMVideo.createInputSWF();</script>
<% end %>