config/routes.rb
Arpameeting::Application.routes.draw do
  get "recharges/new"

  get "recharges/create"

  get "new/create"

  get "orders/new"

  get "sessions/new"

  resources :users, :only => [:show, :new, :create, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
 
  resources :orders, :only => [:new, :create]
  resources :recharges, :only => [:new, :create]
 
  resources :rooms
  resources :services, :only => [:index]
  
  
  match 'rooms/:id_room/participants/:id_participant' => 'rooms#show', :as => 'room_participant'
  
  match 'signup'    => 'users#new'
  match 'signin'    => 'sessions#new'
  match 'sessions'  => redirect('signin')
  match 'signout'   => 'sessions#destroy'

  match 'orders/new/express' => 'orders#express',:as => 'express_new_order'

  match 'api' => 'api_docs#index', :as => 'api_docs'

  namespace :api_v1, :path => 'api/1' do
    resources :rooms
    resources :services, :only => [:index]
  end
  

  root :to => "home#index"

end

app/views/layouts/apidocs.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <title>ArpaMeeting API</title>
      <%= stylesheet_link_tag 'apidocs' %>
      <%= javascript_include_tag :defaults %>
  </head>
  <body>
      
    <div id="header" class="container_12">

        <div id="title" class="grid_12 ">
            <h1>ArpaMeeting API Docs</h1>
        </div>

    </div>

    <div id="content" class="container_12">

        <div class="grid_9">
            <%= yield %>
        </div>
    
        <div class="grid_3">
        </div>

    </div>
    
    <div id="footer" class="container_12">
    
        <div class="grid_12 ">
        </div>
    
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArpaMeeting</title>
  <link href='http://fonts.googleapis.com/css?family=Nobile:regular,italic,bold,bolditalic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Expletus+Sans:regular,bold' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.ico" /> 
  <%= stylesheet_link_tag 'grid' %>
  <%= stylesheet_link_tag 'buttons' %>
  <%= stylesheet_link_tag 'arpameeting' %>
  <%= javascript_include_tag :all %>
  <%= javascript_include_tag Service.find_by_name('video').url + '/amvideo.js', :cache => false %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div id="header-warp" class="clearfix">
        <div id="header" class="container_12">
            <div class="grid_6">
                <%= link_to (image_tag 'logo_light.png'), '/' %>
            </div>
            <div class="grid_6" style="padding-top:29px; text-align:right;">
                <% if !signed_in? %>
                    <%= link_to 'Sign in', signin_path, :class => "button green" %>
                <% else %>
                    <div id="menunav">
                        <%= link_to 'Profile', user_path(current_user), :class => "button" %>
                        <%= link_to 'My Rooms', rooms_path, :class => "button" %>
                        <%= link_to 'New Room', new_room_path, :class => "button" %>
                        <%= link_to 'API', api_docs_path, :class => "button" %>
                        <%= link_to 'Sign out', signout_path, :class => "button blue" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div id="content-warp" class="clearfix">
        <div id="content" class="container_12">
            <%= yield %>
        </div>
    </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArpaMeeting</title>
  <link href='http://fonts.googleapis.com/css?family=Nobile:regular,italic,bold,bolditalic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Expletus+Sans:regular,bold' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.ico" /> 
  <%= stylesheet_link_tag 'grid' %>
  <%= stylesheet_link_tag 'buttons' %>
  <%= stylesheet_link_tag 'arpameeting' %>
  <%= javascript_include_tag :all %>
  <%= javascript_include_tag Service.find_by_name('video').url + '/amvideo.js', :cache => false %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div id="header-warp" class="clearfix">
        <div id="header" class="container_12">
            <div class="grid_6">
                <%= link_to (image_tag 'logo_light.png'), '/' %>
            </div>
            <div class="grid_6" style="padding-top:29px; text-align:right;">
                <% if !signed_in? %>
                    <%= link_to 'Sign in', signin_path, :class => "button green" %>
                <% else %>
                    <div id="menunav">
                    <%= link_to 'Profile', user_path(current_user), :class => "button" %>
                    <%= link_to 'My Rooms', rooms_path, :class => "button" %>
                    <%= link_to 'New Room', new_room_path, :class => "button" %>
                    <%= link_to 'API', api_docs_path, :class => "button" %>
                    <%= link_to 'Sign out', signout_path, :class => "button blue" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <%= yield %>
</body>
</html>